# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(761, 327)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(761, 327))
        MainWindow.setMaximumSize(QtCore.QSize(761, 327))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/L2S13feb/win_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8("selection-background-color: rgb(164, 255, 214);"))
        MainWindow.setIconSize(QtCore.QSize(64, 64))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.Overalllayout = QtGui.QFrame(self.centralwidget)
        self.Overalllayout.setGeometry(QtCore.QRect(0, 0, 761, 291))
        self.Overalllayout.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Overalllayout.setFrameShadow(QtGui.QFrame.Raised)
        self.Overalllayout.setObjectName(_fromUtf8("Overalllayout"))
        self.line = QtGui.QFrame(self.Overalllayout)
        self.line.setGeometry(QtCore.QRect(420, 20, 20, 221))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.converbt = QtGui.QPushButton(self.Overalllayout)
        self.converbt.setGeometry(QtCore.QRect(540, 190, 141, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.converbt.setFont(font)
        self.converbt.setStatusTip(_fromUtf8(""))
        self.converbt.setStyleSheet(_fromUtf8(""))
        self.converbt.setCheckable(False)
        self.converbt.setAutoDefault(False)
        self.converbt.setDefault(False)
        self.converbt.setFlat(False)
        self.converbt.setObjectName(_fromUtf8("converbt"))
        self.Fileasinput_2 = QtGui.QGroupBox(self.Overalllayout)
        self.Fileasinput_2.setGeometry(QtCore.QRect(460, 10, 291, 141))
        self.Fileasinput_2.setObjectName(_fromUtf8("Fileasinput_2"))
        self.label2 = QtGui.QLabel(self.Fileasinput_2)
        self.label2.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.label2.setObjectName(_fromUtf8("label2"))
        self.fileprgssbr = QtGui.QProgressBar(self.Fileasinput_2)
        self.fileprgssbr.setEnabled(True)
        self.fileprgssbr.setGeometry(QtCore.QRect(10, 90, 261, 16))
        self.fileprgssbr.setStatusTip(_fromUtf8(""))
        self.fileprgssbr.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly|QtCore.Qt.ImhPreferNumbers)
        self.fileprgssbr.setProperty("value", 0)
        self.fileprgssbr.setInvertedAppearance(False)
        self.fileprgssbr.setObjectName(_fromUtf8("fileprgssbr"))
        self.fileasinp = QtGui.QRadioButton(self.Fileasinput_2)
        self.fileasinp.setGeometry(QtCore.QRect(270, 10, 16, 17))
        self.fileasinp.setStatusTip(_fromUtf8(""))
        self.fileasinp.setObjectName(_fromUtf8("fileasinp"))
        self.selectfile = QtGui.QToolButton(self.Fileasinput_2)
        self.selectfile.setGeometry(QtCore.QRect(250, 60, 25, 21))
        self.selectfile.setStatusTip(_fromUtf8(""))
        self.selectfile.setIconSize(QtCore.QSize(19, 19))
        self.selectfile.setObjectName(_fromUtf8("selectfile"))
        self.fileclear = QtGui.QToolButton(self.Fileasinput_2)
        self.fileclear.setGeometry(QtCore.QRect(220, 120, 61, 19))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fileclear.setFont(font)
        self.fileclear.setStatusTip(_fromUtf8(""))
        self.fileclear.setStyleSheet(_fromUtf8(""))
        self.fileclear.setObjectName(_fromUtf8("fileclear"))
        self.selectedfileedit = QtGui.QLineEdit(self.Fileasinput_2)
        self.selectedfileedit.setGeometry(QtCore.QRect(10, 60, 241, 20))
        self.selectedfileedit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.selectedfileedit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.selectedfileedit.setDragEnabled(True)
        self.selectedfileedit.setObjectName(_fromUtf8("selectedfileedit"))
        self.Latexasinput = QtGui.QGroupBox(self.Overalllayout)
        self.Latexasinput.setGeometry(QtCore.QRect(10, 10, 391, 261))
        self.Latexasinput.setObjectName(_fromUtf8("Latexasinput"))
        self.Inputareascroll = QtGui.QScrollArea(self.Latexasinput)
        self.Inputareascroll.setGeometry(QtCore.QRect(10, 60, 361, 171))
        self.Inputareascroll.setWidgetResizable(True)
        self.Inputareascroll.setObjectName(_fromUtf8("Inputareascroll"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 359, 169))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.Input1 = QtGui.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.Input1.setGeometry(QtCore.QRect(0, 0, 361, 171))
        self.Input1.setMouseTracking(False)
        self.Input1.setStatusTip(_fromUtf8(""))
        self.Input1.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Input1.setOverwriteMode(True)
        self.Input1.setObjectName(_fromUtf8("Input1"))
        self.Inputareascroll.setWidget(self.scrollAreaWidgetContents)
        self.label1 = QtGui.QLabel(self.Latexasinput)
        self.label1.setGeometry(QtCore.QRect(10, 30, 91, 16))
        self.label1.setObjectName(_fromUtf8("label1"))
        self.txtasinp = QtGui.QRadioButton(self.Latexasinput)
        self.txtasinp.setGeometry(QtCore.QRect(370, 10, 16, 17))
        self.txtasinp.setStatusTip(_fromUtf8(""))
        self.txtasinp.setObjectName(_fromUtf8("txtasinp"))
        self.txtclear = QtGui.QToolButton(self.Latexasinput)
        self.txtclear.setGeometry(QtCore.QRect(310, 240, 61, 19))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtclear.setFont(font)
        self.txtclear.setStatusTip(_fromUtf8(""))
        self.txtclear.setStyleSheet(_fromUtf8(""))
        self.txtclear.setObjectName(_fromUtf8("txtclear"))
        self.convertprgss = QtGui.QProgressBar(self.Overalllayout)
        self.convertprgss.setGeometry(QtCore.QRect(0, 280, 761, 5))
        self.convertprgss.setStatusTip(_fromUtf8(""))
        self.convertprgss.setProperty("value", 0)
        self.convertprgss.setTextVisible(False)
        self.convertprgss.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.convertprgss.setObjectName(_fromUtf8("convertprgss"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 761, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setStyleSheet(_fromUtf8("border-right-color: rgb(6, 6, 6);\n"
"background-color: rgb(221, 221, 221);"))
        self.menuFile.setTearOffEnabled(False)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setStyleSheet(_fromUtf8("\n"
"background-color: rgb(221, 221, 221);"))
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuAbout_2 = QtGui.QMenu(self.menubar)
        self.menuAbout_2.setStyleSheet(_fromUtf8("\n"
"background-color: rgb(221, 221, 221);"))
        self.menuAbout_2.setObjectName(_fromUtf8("menuAbout_2"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setCheckable(True)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionExit_2 = QtGui.QAction(MainWindow)
        self.actionExit_2.setMenuRole(QtGui.QAction.QuitRole)
        self.actionExit_2.setObjectName(_fromUtf8("actionExit_2"))
        self.openfile = QtGui.QAction(MainWindow)
        self.openfile.setObjectName(_fromUtf8("openfile"))
        self.Open = QtGui.QAction(MainWindow)
        self.Open.setStatusTip(_fromUtf8(""))
        self.Open.setObjectName(_fromUtf8("Open"))
        self.exit = QtGui.QAction(MainWindow)
        self.exit.setStatusTip(_fromUtf8(""))
        self.exit.setMenuRole(QtGui.QAction.QuitRole)
        self.exit.setObjectName(_fromUtf8("exit"))
        self.mConvert = QtGui.QAction(MainWindow)
        self.mConvert.setStatusTip(_fromUtf8(""))
        self.mConvert.setObjectName(_fromUtf8("mConvert"))
        self.about = QtGui.QAction(MainWindow)
        self.about.setStatusTip(_fromUtf8(""))
        self.about.setObjectName(_fromUtf8("about"))
        self.menuFile.addAction(self.Open)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.exit)
        self.menuAbout.addAction(self.mConvert)
        self.menuAbout_2.addAction(self.about)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menuAbout_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.exit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.Input1, QtCore.SIGNAL(_fromUtf8("textChanged()")), self.txtasinp.toggle)
        QtCore.QObject.connect(self.selectfile, QtCore.SIGNAL(_fromUtf8("clicked()")), self.fileasinp.toggle)
        QtCore.QObject.connect(self.selectedfileedit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), self.fileasinp.toggle)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Latex to Speech", None))
        self.converbt.setText(_translate("MainWindow", "Convert", None))
        self.converbt.setShortcut(_translate("MainWindow", "Ctrl+C", None))
        self.Fileasinput_2.setTitle(_translate("MainWindow", "File as Input:", None))
        self.label2.setText(_translate("MainWindow", "Select the file:", None))
        self.fileasinp.setText(_translate("MainWindow", "RadioButton", None))
        self.selectfile.setText(_translate("MainWindow", "...", None))
        self.fileclear.setText(_translate("MainWindow", "Clear", None))
        self.selectedfileedit.setText(_translate("MainWindow", "--Select--", None))
        self.Latexasinput.setTitle(_translate("MainWindow", "LaTeX as Input:", None))
        self.label1.setText(_translate("MainWindow", "Enter the Input:", None))
        self.txtasinp.setText(_translate("MainWindow", "RadioButton", None))
        self.txtclear.setText(_translate("MainWindow", "Clear", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuAbout.setTitle(_translate("MainWindow", "Run", None))
        self.menuAbout_2.setTitle(_translate("MainWindow", "About", None))
        self.actionNew.setText(_translate("MainWindow", "New", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionOpen.setStatusTip(_translate("MainWindow", "Click to open file..", None))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionExit_2.setText(_translate("MainWindow", "Exit", None))
        self.openfile.setText(_translate("MainWindow", "Open file", None))
        self.openfile.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.Open.setText(_translate("MainWindow", "Open", None))
        self.Open.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.exit.setText(_translate("MainWindow", "Exit", None))
        self.mConvert.setText(_translate("MainWindow", "Convert", None))
        self.mConvert.setShortcut(_translate("MainWindow", "Ctrl+R", None))
        self.about.setText(_translate("MainWindow", "About", None))

#import icon_rc
